spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamesearch}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

gamesearch:
  security:
    secret: "${JWT_SECRET:secret-word}"
